<a href="https://colab.research.google.com/github/Lih01/Deep-Learning-w-PyTorch/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor ([1,2,3,4])
tensor_b = torch.tensor ([5,6,7,8])

# Soma

In [6]:
# A soma dos itens correspondem a sua localização (1+5, 2+6, 3+7, 4+8,) e assim
# segue, mas é importante ter as mesmas quantidade
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
# Adição "a mão"
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

# Subtração

In [8]:
# Mesma ideia da soma, mas agora subtraindo
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [9]:
# Subtração "a mão"
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

# Multiplicação

In [10]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [12]:
# Multiplição "a mão"
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

# Divisão

In [14]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
# Divisão "a mão"
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

"Restos" da divisão usamos o Módulo (%)

In [16]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [17]:
# Restos "à mão"
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

# Expoentes (x²)

In [20]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [21]:
# Expoente "à mão"
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

# Outros meios

*   tensor_a.add();
*   tensor_b.sun();
*   tensor_a.mul();
*   tensor_b.div();
*   tensor_b.remainder();
*   tensor_a.pow()

# Reatribuição (Reassignment)

In [23]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [24]:
tensor_a

tensor([1, 2, 3, 4])

In [31]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)
# e cada vez q você rodar essa parte do código, vai sempre adicionando os valores

tensor([36, 44, 52, 60])