<a href="https://colab.research.google.com/github/Lih01/Deep-Learning-w-PyTorch/blob/main/Tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Reshape and view
my_torch = my_torch.reshape(2,5)
my_torch
# Tem q fazer sentido quando for refomular a forma

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
# Reshape is we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_torch2 = my_torch2.reshape(2,-1)
# Ou pode ser (-1,5) pois irá dar o mesmo valor
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# **Diferença entre Reshape e View:**
In PyTorch, both reshape() and view() are used to change the shape of a tensor, but their key difference lies in how they handle memory and whether they return a view or a copy of the original data.

view():
- ***Returns a view:*** attempts to return a new tensor that shares the same underlying data as the original tensor. This means no new memory is allocated for the data.
- ***Requires contiguous memory:*** to succeed, the original tensor's memory must be "contiguous." This means the elements are stored sequentially in memory. If the tensor is not contiguous (e.g., after slicing operations), view() will raise a RuntimeError.
- ***Changes reflect in both:*** Because view() creates a view, any in-place modifications to the returned tensor will also affect the original tensor, and vice versa.

reshape():
- ***Returns a view or a copy:*** is more flexible. It will return a view of the original tensor if the new shape is compatible with the existing memory layout (i.e., if a view can be created). However, if the tensor is not contiguous or the new shape requires a different memory layout, reshape() will automatically create a copy of the data to ensure the new tensor is contiguous.
- ***Does not require contiguous memory:*** handles non-contiguous tensors by performing a copy when necessary, making it more robust in various scenarios.
- ***Changes might not reflect:*** If creates a copy, then changes made to the new tensor will not affect the original tensor, as they are distinct entities in memory.

In summary:
- ***Use view() when:***
You are confident the tensor is contiguous and you want a memory-efficient operation where changes to one tensor reflect in the other.
- ***Use reshape() when:***
You need to reshape a tensor and are unsure about its memory contiguity, or you don't require shared memory and are comfortable with a potential data copy. reshape() is generally safer and more convenient as it handles contiguity automatically.

In [9]:
# W/ reshape and view, they will update
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
my_torch4 = my_torch3.reshape(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
my_torch3[1] = 4141
my_torch3

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [12]:
my_torch4

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

# Slices

In [13]:
my_torch5 = torch.arange(10)
my_torch5


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# Pegar um item específico
my_torch5[7] #Não é realmente o número 7

tensor(7)

In [16]:
# Pegar um pedaço (slice)
my_torch6 = my_torch5.reshape(5,2)
my_torch6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [22]:
my_torch6[:,1]

tensor([1, 3, 5, 7, 9])

In [23]:
# Return colum
my_torch6[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])