<a href="https://colab.research.google.com/github/Lih01/Deep-Learning-w-PyTorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

# Listas

In [5]:
my_list = [2, 5, 7, 9]
my_list

[2, 5, 7, 9]

# Numpy Arrays
Tem uma playlist se quiser se aprofundar mais:
[Intro Numpy](https://www.youtube.com/playlist?list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK)

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.61886416, 0.49036901, 0.6135322 , 0.35302244],
       [0.66423154, 0.36715461, 0.13714008, 0.18264852],
       [0.98568706, 0.35455924, 0.0435668 , 0.49028053]])

In [8]:
np1.dtype

dtype('float64')

# Tensors

In [10]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 2.0767e+00,  9.8587e-01,  1.3218e+00,  2.7578e-01],
        [-9.3159e-01, -3.1017e-01, -6.9709e-01, -1.0459e+00],
        [-1.7733e-03, -7.8657e-01, -1.6545e-01,  1.2350e+00]])

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
# Criar tensor com numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6189, 0.4904, 0.6135, 0.3530],
        [0.6642, 0.3672, 0.1371, 0.1826],
        [0.9857, 0.3546, 0.0436, 0.4903]], dtype=torch.float64)